project_path: "/scr1/users/torresdizm/"
samples_file: "metadata/samples.tsv"
comparisons_file: "metadata/Target_Samples.txt"
bam_path: "/mnt/isilon/thomas-tikhonenko_lab/target/processed_reads/"
gtf_anno: "/scr1/users/torresdizm/genomes/GRCh38.p13/gencode.v33.annotation.gtf"